In [1]:
import pandas as pd

artigo_treino = pd.read_csv("./database/treino.csv")
artigo_teste = pd.read_csv("./database/teste.csv")

In [2]:
artigo_treino.sample(5)

title  \
33829  'Leniência', a palavra que resume o primeiro s...   
71321  Com Trump presidente, um de seus eleitores não...   
39674  Crítica - Peça recria 'Senhorita Julia' com br...   
37833  Eleição nos EUA mostra que analistas precisam ...   
27019  'Westworld' lidera indicações ao Emmy 2017 e c...   

                                                    text        date  \
33829  O substantivo "leniência" é a Palavra do Semes...  2017-06-07   
71321  RIO DE JANEIRO - Um amigo meu, filho de brasil...  2016-07-30   
39674  Embora desloque o eixo dramático do conhecido ...  2015-03-16   
37833  "[Donald Trump] não precisa do Colorado ou da ...  2016-12-11   
27019  Os indicados à 69ª edição do Emmy, principal p...  2017-07-13   

        category       subcategory  \
33829    colunas  sergio-rodrigues   
71321    colunas         ruycastro   
39674  ilustrada               NaN   
37833      mundo               NaN   
27019  ilustrada               NaN   

                                                    link  
33829  http://www1.folha.uol.com.br/colunas/sergio-ro...  
71321  http://www1.folha.uol.com.br/colunas/ruycastro...  
39674  http://www1.folha.uol.com.br/ilustrada/2015/03...  
37833  http://www1.folha.uol.com.br/mundo/2016/11/183...  
27019  http://www1.folha.uol.com.br/ilustrada/2017/07...

In [3]:
artigo_teste.iloc[643].title

'Somos todos imprevisíveis'

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

texto = [
    "tenha um bom dia",
    "tenha um péssimo dia",
    "tenha um ótimo dia",
    "tenha um dia ruim"
]

vetorizador = CountVectorizer()
vetorizador.fit(texto)

CountVectorizer()

In [5]:
vetorizador.vocabulary_

{'tenha': 4, 'um': 5, 'bom': 0, 'dia': 1, 'péssimo': 2, 'ótimo': 6, 'ruim': 3}

In [6]:
vetor_bom = vetorizador.transform(["bom"])
vetor_bom.toarray()

array([[1, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [7]:
vetor_ótimo = vetorizador.transform(["ótimo"])
vetor_ótimo.toarray()

array([[0, 0, 0, 0, 0, 0, 1]], dtype=int64)

In [ ]:
with open("./database/cbow_s300.txt") as f:
    for line in range(10):
        print(next(f))

In [9]:
!pip install gensim
from gensim.models import KeyedVectors

modelo = KeyedVectors.load_word2vec_format("./database/cbow_s300.txt")

You should consider upgrading via the 'c:\users\pedro\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.
C:\Users\Pedro\AppData\Local\Programs\Python\Python38\lib\site-packages\gensim\similarities\__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)


In [10]:
modelo.get_vector("china")

array([-1.49033e-01,  1.26020e-01,  2.17628e-01,  1.82684e-01,
        1.65151e-01, -1.59660e-01, -2.34411e-01,  6.00570e-02,
        8.03680e-02,  2.87578e-01, -4.81100e-03, -5.68800e-02,
        2.15676e-01,  8.65540e-02,  1.25983e-01,  3.36157e-01,
       -1.83254e-01, -1.18499e-01,  1.13010e-02,  1.03814e-01,
        9.37640e-02,  2.90178e-01, -1.64395e-01, -1.13300e-02,
       -1.80676e-01, -1.15820e-02,  1.08728e-01,  1.65898e-01,
        9.37900e-02,  2.66767e-01, -1.29890e-02,  9.16030e-02,
        2.21292e-01, -1.36497e-01, -4.26350e-02, -1.30038e-01,
        2.17067e-01, -1.01963e-01, -3.70960e-02,  1.42155e-01,
        3.41109e-01,  2.46560e-01,  1.27458e-01,  5.72360e-02,
       -1.47962e-01, -1.60290e-02,  1.86533e-01,  7.71550e-02,
       -3.50024e-01, -4.06085e-01,  1.67131e-01, -4.75230e-02,
        5.13780e-02, -1.28224e-01,  1.06580e-02, -2.92652e-01,
        1.40540e-01, -4.57049e-01,  1.31094e-01,  2.03234e-01,
        2.94019e-01,  7.38370e-02,  1.11554e-01, -1.642

In [11]:
modelo.most_similar("china")

[('rússia', 0.7320705056190491),
 ('índia', 0.7241616249084473),
 ('tailândia', 0.701935887336731),
 ('indonésia', 0.6860769987106323),
 ('turquia', 0.6741335988044739),
 ('malásia', 0.6665689945220947),
 ('mongólia', 0.6593616008758545),
 ('manchúria', 0.658184826374054),
 ('urss', 0.6581669449806213),
 ('grã-bretanha', 0.6568097472190857)]

In [12]:
modelo.most_similar(positive=["brasil","argentina"])

[('chile', 0.6781662702560425),
 ('peru', 0.634803295135498),
 ('venezuela', 0.6273865699768066),
 ('equador', 0.6037014126777649),
 ('bolívia', 0.6017141342163086),
 ('haiti', 0.5993806719779968),
 ('méxico', 0.596230685710907),
 ('paraguai', 0.5957703590393066),
 ('uruguai', 0.590367317199707),
 ('japão', 0.5893509387969971)]

In [13]:
#nuvens -> nuvem : estrelas - estrela
#nuvens + estrela - nuvem = estrelas

modelo.most_similar(positive=["nuvens","estrela"],negative=["nuvem"])

[('estrelas', 0.5497430562973022),
 ('plêiades', 0.3791979253292084),
 ('colinas', 0.3746805489063263),
 ('trovoadas', 0.373703271150589),
 ('sombras', 0.37341946363449097),
 ('pombas', 0.3726757764816284),
 ('corredoras', 0.3640727400779724),
 ('cigarras', 0.36065396666526794),
 ('galáxias', 0.35754913091659546),
 ('luas', 0.3575345277786255)]

In [14]:
modelo.most_similar(positive=["médico","mulher"],negative=["homem"])

[('enfermeira', 0.6180862784385681),
 ('psicóloga', 0.47447532415390015),
 ('dama-de-companhia', 0.47382354736328125),
 ('esposa', 0.46559134125709534),
 ('parteira', 0.46362870931625366),
 ('mãe', 0.45817679166793823),
 ('governanta', 0.45722925662994385),
 ('madrasta', 0.4569782614707947),
 ('menina', 0.44435903429985046),
 ('filha', 0.44341111183166504)]

In [15]:
modelo.most_similar(positive=["professor","mulher"],negative=["homem"])

[('professora', 0.6192208528518677),
 ('aluna', 0.5449554324150085),
 ('esposa', 0.4978230893611908),
 ('ex-aluna', 0.4884248673915863),
 ('namorada', 0.4737858772277832),
 ('enfermeira', 0.4728144407272339),
 ('filha', 0.467373788356781),
 ('irmã', 0.4584590792655945),
 ('ex-namorada', 0.45824769139289856),
 ('ex-professora', 0.45104706287384033)]

## Vetorização de texto

In [16]:
artigo_treino.title.loc[12]

"Daniel Craig será stormtrooper em novo 'Star Wars', diz ator"

In [17]:
import nltk
import string

#nltk.download('punkt')

def tokenizador(texto):
    texto = texto.lower()
    lista_alfanumerico = []

    for token_valido in nltk.word_tokenize(texto):
        if token_valido in string.punctuation: continue
        lista_alfanumerico.append(token_valido)

    return lista_alfanumerico

tokenizador("Pedro grande sabio, 1234")

['pedro', 'grande', 'sabio', '1234']

In [18]:
import numpy as np

def combinacao_de_vetores_por_soma(palavras_numeros):
    vertor_resultante = np.zeros(300)
    for pn in palavras_numeros:
        try:
            vertor_resultante += modelo.get_vector(pn)
        except KeyError:
            if pn.isnumeric():
                pn = "0"*len(pn)
                vertor_resultante += modelo.get_vector(pn)
            else:
                vertor_resultante += modelo.get_vector("unknown")
    return vertor_resultante

In [ ]:
palavras_numeros = tokenizador("texto exemplo 1")
vetor_texto = combinacao_de_vetores_por_soma(palavras_numeros)
print(len(vetor_texto))
print(vetor_texto)

In [20]:
def matriz_vetores(textos):
    x = len(textos)
    y = 300
    matriz = np.zeros((x,y))

    for i in range(x):
        palavras_numeros = tokenizador(textos.iloc[i])
        matriz[i] = combinacao_de_vetores_por_soma(palavras_numeros)
    return matriz


matriz_vetores_treino = matriz_vetores(artigo_treino.title)
matriz_vetores_teste = matriz_vetores(artigo_teste.title)

print(matriz_vetores_treino.shape)
print(matriz_vetores_teste.shape)

(90000, 300)
(20513, 300)


In [21]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression(max_iter = 200)
LR.fit(matriz_vetores_treino, artigo_treino.category)

LogisticRegression(max_iter=200)

In [22]:
LR.score(matriz_vetores_teste, artigo_teste.category)

0.7957880368546775

In [23]:
from sklearn.metrics import classification_report

label_prevista = LR.predict(matriz_vetores_teste)
CR = classification_report(artigo_teste.category, label_prevista)
print(CR)

              precision    recall  f1-score   support

     colunas       0.86      0.71      0.78      6103
   cotidiano       0.61      0.79      0.69      1698
     esporte       0.92      0.88      0.90      4663
   ilustrada       0.13      0.88      0.23       131
     mercado       0.84      0.79      0.81      5867
       mundo       0.74      0.86      0.79      2051

    accuracy                           0.80     20513
   macro avg       0.68      0.82      0.70     20513
weighted avg       0.83      0.80      0.81     20513



In [24]:
from sklearn.dummy import DummyClassifier

DC = DummyClassifier()
DC.fit(matriz_vetores_treino, artigo_treino.category)
label_prevista_dc = DC.predict(matriz_vetores_teste)

CR_dummy = classification_report(artigo_teste.category, label_prevista_dc)
print(CR_dummy)

C:\Users\Pedro\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\dummy.py:131: FutureWarning: The default value of strategy will change from stratified to prior in 0.24.
  warnings.warn("The default value of strategy will change from "


              precision    recall  f1-score   support

     colunas       0.30      0.17      0.22      6103
   cotidiano       0.08      0.16      0.11      1698
     esporte       0.23      0.17      0.20      4663
   ilustrada       0.01      0.18      0.01       131
     mercado       0.30      0.17      0.22      5867
       mundo       0.10      0.17      0.12      2051

    accuracy                           0.17     20513
   macro avg       0.17      0.17      0.15     20513
weighted avg       0.24      0.17      0.19     20513



In [25]:
modelo_skipgram = KeyedVectors.load_word2vec_format("./database/skip_s300.txt")




In [26]:
def combinacao_de_vetores_por_soma_skipgram(palavras_numeros):
    vertor_resultante = np.zeros(300)
    for pn in palavras_numeros:
        try:
            vertor_resultante += modelo_skipgram.get_vector(pn)
        except KeyError:
            if pn.isnumeric():
                pn = "0"*len(pn)
                vertor_resultante += modelo_skipgram.get_vector(pn)
            else:
                vertor_resultante += modelo_skipgram.get_vector("unknown")
    return vertor_resultante

def matriz_vetores_skipgram(textos):
    x = len(textos)
    y = 300
    matriz = np.zeros((x,y))

    for i in range(x):
        palavras_numeros = tokenizador(textos.iloc[i])
        matriz[i] = combinacao_de_vetores_por_soma_skipgram(palavras_numeros)
    return matriz


In [27]:
matriz_vetores_treino_skipgram = matriz_vetores_skipgram(artigo_treino.title)
matriz_vetores_teste_skipgram = matriz_vetores_skipgram(artigo_teste.title)

#Previsão
LR_skipgram = LogisticRegression(max_iter=1000)

LR_skipgram.fit(matriz_vetores_treino_skipgram, artigo_treino.category)
label_previsao_skipgram = LR_skipgram.predict(matriz_vetores_teste_skipgram)
CR_skipgram = classification_report(artigo_teste.category, label_previsao_skipgram )
print(CR_skipgram)

              precision    recall  f1-score   support

     colunas       0.86      0.72      0.78      6103
   cotidiano       0.63      0.81      0.70      1698
     esporte       0.93      0.89      0.91      4663
   ilustrada       0.15      0.91      0.26       131
     mercado       0.84      0.81      0.83      5867
       mundo       0.76      0.86      0.80      2051

    accuracy                           0.81     20513
   macro avg       0.69      0.83      0.71     20513
weighted avg       0.84      0.81      0.82     20513

